version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studio-web
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: studio-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studio_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: studio-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: userpass
    ports:
      - "8080:80"
